# Generated by Django 4.0.2 on 2022-03-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0002_allow_blank_null_for_datetime_fields'),
        ('evas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eva',
            name='seq_code_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eva',
            name='astronaut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evas', to='astronauts.astronaut'),
        ),
    ]
