# Generated by Django 4.0.2 on 2022-03-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evas', '0002_add_eva_seq_code_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eva',
            old_name='seq_code_number',
            new_name='code',
        ),
    ]
