# Generated by Django 4.0.2 on 2022-03-07 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astronaut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('nick_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('birth_town_city', models.CharField(blank=True, max_length=50)),
                ('birth_state', models.CharField(blank=True, max_length=50)),
                ('birth_country', models.CharField(blank=True, max_length=50)),
                ('death_date', models.DateField()),
                ('resting_place', models.CharField(blank=True, max_length=50)),
                ('rank_attained', models.CharField(max_length=100)),
                ('service_branch', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('first_time_in_space_date', models.DateField()),
                ('total_duration_space_secs', models.DurationField()),
                ('retirement_date', models.DateField()),
                ('image_photo', models.ImageField(blank=True, upload_to='astronaut/photos')),
                ('image_signature', models.ImageField(blank=True, upload_to='astronaut/signatures')),
                ('wikipedia_bio_website', models.URLField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['first_time_in_space_date'],
            },
        ),
    ]
