# Generated by Django 4.0.2 on 2022-03-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='astronaut',
            name='retirement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
