# Generated by Django 4.0.2 on 2022-03-03 14:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('date_formed', models.DateField(null=True)),
                ('website', models.URLField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
            },
        ),
    ]
