# Generated by Django 4.0.2 on 2022-03-07 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='date_formed',
        ),
        migrations.AddField(
            model_name='agency',
            name='formed_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
