# Generated by Django 4.0.2 on 2022-03-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_change_to_date_formed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='formed_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
