# Generated by Django 4.0.2 on 2022-03-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("astronauts", "0002_allow_blank_null_for_datetime_fields"),
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="crew_members",
            field=models.ManyToManyField(to="astronauts.Astronaut"),
        ),
        migrations.AddField(
            model_name="mission",
            name="crew_size",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
