# Generated by Django 4.0.2 on 2022-03-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_add_crew_to_mission_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='image_mission_patch',
            field=models.ImageField(blank=True, upload_to='mission/patch'),
        ),
    ]
