# Generated by Django 4.0.2 on 2022-03-25 09:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('astronauts', '0002_allow_blank_null_for_datetime_fields'),
        ('missions', '0003_add_image_mission_patch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=50)),
                ('mission_age', models.DurationField()),
                ('crew_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astronauts.astronaut')),
            ],
        ),
        migrations.RemoveField(
            model_name='mission',
            name='crew_members',
        ),
        migrations.AddField(
            model_name='mission',
            name='crew_member',
            field=models.ManyToManyField(through='missions.Crew', to='astronauts.Astronaut'),
        ),
        migrations.AddField(
            model_name='crew',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission'),
        ),
    ]
