# Generated by Django 4.0.2 on 2022-03-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_add_crew_model_via_through_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crew',
            options={'ordering': ['mission']},
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='crew_member',
            new_name='crew_members',
        ),
    ]
