# Generated by Django 5.1.6 on 2025-02-17 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agencies", "0003_allow_formed_date_blank_null"),
        ("missions", "0006_revise_crew_model"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mission",
            name="crew_size",
        ),
        migrations.AlterField(
            model_name="mission",
            name="agency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="agencies.agency",
            ),
        ),
    ]
